BEGIN
   FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN (
       'CUSTOMER_SEQ', 'BOOKING_SEQ', 'TICKET_SEQ', 'PAYMENT_SEQ', 'REFUND_SEQ', 
       'REVIEW_SEQ', 'NOTIFICATION_SEQ', 'AUDIT_LOG_SEQ', 'FOOD_ORDER_SEQ', 'SHOW_SEAT_SEQ')) 
   LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
   END LOOP;
END;
/

CREATE SEQUENCE CUSTOMER_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BOOKING_SEQ START WITH 5000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TICKET_SEQ START WITH 7000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PAYMENT_SEQ START WITH 8000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE REFUND_SEQ START WITH 9000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE REVIEW_SEQ START WITH 3000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NOTIFICATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FOOD_ORDER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SHOW_SEAT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
