BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FAVORITES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REVIEWS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REFUNDS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PAYMENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COUPONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FOOD_ORDERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FOOD CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TICKETS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BOOKINGS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHOW_SEATS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHOWS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEATS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SCREENS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE THEATRES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MOVIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOCATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    MOBILE VARCHAR2(15) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255),
    ROLE VARCHAR2(20) DEFAULT 'CUSTOMER' CHECK (ROLE IN ('CUSTOMER','ADMIN','THEATRE_MANAGER')),
    SUPABASE_ID VARCHAR2(100),
    PROFILE_IMAGE VARCHAR2(500),
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE LOCATIONS (
    LOCATION_ID NUMBER PRIMARY KEY,
    CITY VARCHAR2(100) NOT NULL,
    STATE VARCHAR2(100),
    COUNTRY VARCHAR2(100) DEFAULT 'India',
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

CREATE TABLE MOVIES (
    MOVIE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION CLOB,
    LANGUAGE VARCHAR2(50),
    GENRE VARCHAR2(100),
    DURATION_MINUTES NUMBER NOT NULL,
    RELEASE_DATE DATE,
    CERTIFICATE VARCHAR2(10),
    RATING NUMBER(3,1) DEFAULT 0 CHECK (RATING >= 0 AND RATING <= 5),
    STATUS VARCHAR2(20) DEFAULT 'RUNNING' CHECK (STATUS IN ('RUNNING','UPCOMING','COMPLETED','CANCELLED')),
    POSTER_URL VARCHAR2(500),
    BACKDROP_URL VARCHAR2(500),
    TRAILER_URL VARCHAR2(500),
    DIRECTOR VARCHAR2(200),
    CAST_INFO VARCHAR2(1000),
    FORMAT VARCHAR2(50) DEFAULT '2D',
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE THEATRES (
    THEATRE_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    LOCATION_ID NUMBER REFERENCES LOCATIONS(LOCATION_ID),
    ADDRESS VARCHAR2(500),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    RATING NUMBER(3,1) DEFAULT 0,
    AMENITIES VARCHAR2(500),
    PHONE VARCHAR2(20),
    EMAIL VARCHAR2(150),
    MANAGER_ID NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID) NULL,
    LICENSE_NUMBER VARCHAR2(100),
    GSTIN VARCHAR2(20),
    FIRE_SAFETY_NOC VARCHAR2(100),
    VERIFICATION_STATUS VARCHAR2(30) DEFAULT 'PENDING' CHECK (VERIFICATION_STATUS IN ('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED')),
    VERIFIED_AT DATE,
    VERIFIED_BY NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID),
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

CREATE TABLE SCREENS (
    SCREEN_ID NUMBER PRIMARY KEY,
    THEATRE_ID NUMBER NOT NULL REFERENCES THEATRES(THEATRE_ID),
    SCREEN_NAME VARCHAR2(50) NOT NULL,
    SCREEN_TYPE VARCHAR2(50) DEFAULT '2D',
    TOTAL_SEATS NUMBER NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

CREATE TABLE SEATS (
    SEAT_ID NUMBER PRIMARY KEY,
    SCREEN_ID NUMBER NOT NULL REFERENCES SCREENS(SCREEN_ID),
    ROW_NAME VARCHAR2(5) NOT NULL,
    SEAT_NUMBER NUMBER NOT NULL,
    SEAT_TYPE VARCHAR2(20) DEFAULT 'REGULAR' CHECK (SEAT_TYPE IN ('REGULAR','PREMIUM','RECLINER','ACCESSIBLE')),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    UNIQUE(SCREEN_ID, ROW_NAME, SEAT_NUMBER)
);

CREATE TABLE SHOWS (
    SHOW_ID NUMBER PRIMARY KEY,
    MOVIE_ID NUMBER NOT NULL REFERENCES MOVIES(MOVIE_ID),
    SCREEN_ID NUMBER NOT NULL REFERENCES SCREENS(SCREEN_ID),
    SHOW_DATE DATE NOT NULL,
    SHOW_TIME VARCHAR2(10) NOT NULL,
    FORMAT VARCHAR2(20) DEFAULT '2D',
    BASE_PRICE NUMBER(10,2) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE SHOW_SEATS (
    SHOW_SEAT_ID NUMBER PRIMARY KEY,
    SHOW_ID NUMBER NOT NULL REFERENCES SHOWS(SHOW_ID),
    SEAT_ID NUMBER NOT NULL REFERENCES SEATS(SEAT_ID),
    STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (STATUS IN ('AVAILABLE','LOCKED','BOOKED','CANCELLED')),
    LOCKED_AT DATE,
    LOCKED_BY NUMBER,
    PRICE NUMBER(10,2),
    UNIQUE(SHOW_ID, SEAT_ID)
);

CREATE TABLE BOOKINGS (
    BOOKING_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
    SHOW_ID NUMBER NOT NULL REFERENCES SHOWS(SHOW_ID),
    BOOKING_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING','CONFIRMED','CANCELLED','EXPIRED')),
    TOTAL_AMOUNT NUMBER(10,2),
    DISCOUNT_AMOUNT NUMBER(10,2) DEFAULT 0,
    CONVENIENCE_FEE NUMBER(10,2) DEFAULT 0,
    FINAL_AMOUNT NUMBER(10,2),
    COUPON_CODE VARCHAR2(50),
    NUM_SEATS NUMBER,
    SEAT_IDS VARCHAR2(500)
);

CREATE TABLE TICKETS (
    TICKET_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL REFERENCES BOOKINGS(BOOKING_ID),
    SHOW_SEAT_ID NUMBER NOT NULL REFERENCES SHOW_SEATS(SHOW_SEAT_ID),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE','CANCELLED','USED')),
    GENERATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE FOOD (
    FOOD_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CATEGORY VARCHAR2(50),
    PRICE NUMBER(10,2) NOT NULL,
    IMAGE_URL VARCHAR2(500),
    IS_AVAILABLE NUMBER(1) DEFAULT 1,
    IS_VEG NUMBER(1) DEFAULT 1
);

CREATE TABLE FOOD_ORDERS (
    FOOD_ORDER_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL REFERENCES BOOKINGS(BOOKING_ID),
    FOOD_ID NUMBER NOT NULL REFERENCES FOOD(FOOD_ID),
    QUANTITY NUMBER NOT NULL CHECK (QUANTITY > 0),
    SUBTOTAL NUMBER(10,2) NOT NULL
);

CREATE TABLE COUPONS (
    COUPON_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(50) UNIQUE NOT NULL,
    DISCOUNT_TYPE VARCHAR2(20) CHECK (DISCOUNT_TYPE IN ('PERCENTAGE','FLAT')),
    DISCOUNT_VALUE NUMBER(10,2) NOT NULL,
    MIN_ORDER_AMOUNT NUMBER(10,2) DEFAULT 0,
    MAX_DISCOUNT NUMBER(10,2),
    USAGE_LIMIT NUMBER,
    USED_COUNT NUMBER DEFAULT 0,
    EXPIRY_DATE DATE,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL REFERENCES BOOKINGS(BOOKING_ID),
    AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(30) CHECK (PAYMENT_METHOD IN ('UPI','CARD','NET_BANKING','WALLET')),
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (PAYMENT_STATUS IN ('PENDING','COMPLETED','FAILED','REFUNDED')),
    TRANSACTION_REF VARCHAR2(100),
    PAYMENT_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE REFUNDS (
    REFUND_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL REFERENCES BOOKINGS(BOOKING_ID),
    PAYMENT_ID NUMBER REFERENCES PAYMENTS(PAYMENT_ID),
    AMOUNT NUMBER(10,2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'INITIATED' CHECK (STATUS IN ('INITIATED','PROCESSING','COMPLETED','FAILED')),
    REFUND_METHOD VARCHAR2(30),
    REFUND_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE REVIEWS (
    REVIEW_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
    MOVIE_ID NUMBER NOT NULL REFERENCES MOVIES(MOVIE_ID),
    RATING NUMBER CHECK (RATING >= 1 AND RATING <= 5),
    REVIEW_TEXT CLOB,
    CREATED_AT DATE DEFAULT SYSDATE,
    UNIQUE(CUSTOMER_ID, MOVIE_ID)
);

CREATE TABLE FAVORITES (
    FAVORITE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
    ENTITY_TYPE VARCHAR2(20) CHECK (ENTITY_TYPE IN ('MOVIE','THEATRE')),
    ENTITY_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    UNIQUE(CUSTOMER_ID, ENTITY_TYPE, ENTITY_ID)
);

CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
    TITLE VARCHAR2(200) NOT NULL,
    MESSAGE VARCHAR2(1000),
    TYPE VARCHAR2(50),
    IS_READ NUMBER(1) DEFAULT 0,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE AUDIT_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    USER_ROLE VARCHAR2(20),
    ACTION VARCHAR2(100) NOT NULL,
    ENTITY_TYPE VARCHAR2(50),
    ENTITY_ID NUMBER,
    DETAILS VARCHAR2(1000),
    CREATED_AT DATE DEFAULT SYSDATE
);
