CREATE OR REPLACE TRIGGER TRG_BOOK_SEAT
AFTER INSERT ON BOOKINGS
FOR EACH ROW
DECLARE
    v_seat_id VARCHAR2(500);
BEGIN
    v_seat_id := :NEW.SEAT_IDS;
    
    -- Simplification: Assuming single seat ID passed in SEAT_IDS for now.
    -- If multiple, a split function loop would be required.
    IF v_seat_id IS NOT NULL THEN
        UPDATE SHOW_SEATS SET STATUS = 'BOOKED' WHERE SHOW_SEAT_ID = TO_NUMBER(v_seat_id);
        
        INSERT INTO TICKETS (TICKET_ID, BOOKING_ID, SHOW_SEAT_ID, STATUS)
        VALUES (TICKET_SEQ.NEXTVAL, :NEW.BOOKING_ID, TO_NUMBER(v_seat_id), 'ACTIVE');
    END IF;
END TRG_BOOK_SEAT;
/

CREATE OR REPLACE TRIGGER TRG_PAYMENT_CONFIRM
AFTER INSERT ON PAYMENTS
FOR EACH ROW
BEGIN
    IF :NEW.PAYMENT_STATUS = 'COMPLETED' THEN
        UPDATE BOOKINGS SET STATUS = 'CONFIRMED' WHERE BOOKING_ID = :NEW.BOOKING_ID;
    END IF;
END TRG_PAYMENT_CONFIRM;
/

CREATE OR REPLACE TRIGGER TRG_RELEASE_SEAT
AFTER UPDATE OF STATUS ON BOOKINGS
FOR EACH ROW
WHEN (NEW.STATUS = 'CANCELLED' AND OLD.STATUS != 'CANCELLED')
DECLARE
    v_seat_id VARCHAR2(500);
BEGIN
    v_seat_id := :NEW.SEAT_IDS;
    
    IF v_seat_id IS NOT NULL THEN
        UPDATE SHOW_SEATS SET STATUS = 'AVAILABLE' WHERE SHOW_SEAT_ID = TO_NUMBER(v_seat_id);
        UPDATE TICKETS SET STATUS = 'CANCELLED' WHERE BOOKING_ID = :NEW.BOOKING_ID;
        
        -- Create a refund record if it was paid
        IF :OLD.STATUS IN ('CONFIRMED') THEN
            INSERT INTO REFUNDS (REFUND_ID, BOOKING_ID, AMOUNT, STATUS)
            VALUES (REFUND_SEQ.NEXTVAL, :NEW.BOOKING_ID, :NEW.FINAL_AMOUNT, 'INITIATED');
        END IF;
    END IF;
END TRG_RELEASE_SEAT;
/
